### ISSUE TITLE
3 Wire Kite

### ISSUE THREAD

**Issue by 1-Bart-1** [aenarete/KiteSimulators.jl#13]
Is there any possibility to simulate a kite that has 3 wires going from the ground to the kite, so using three ground-based motors, instead of using a control pod in the air? If so, how could one implement this?

**Comment by ufechner7** [comment]
Yes, this is possible. But it is not so easy... I move this issue to the KiteModels repository...

**Comment by ufechner7** [comment]
I close this, it is replaced by: https://github.com/ufechner7/KiteModels.jl/issues/45
