### ISSUE TITLE
Package installation error

### ISSUE THREAD

**Issue by AlshaimaaYounis** [aenarete/KiteSimulators.jl#17]
I would be grateful if you could tell me how to fix this error.

After reaching the step > create_sys_image  in the package installation the following error appears:
ERROR: LoadError: KeyError: key "kps4_3l" not found

**Comment by ufechner7** [comment]
I need to create a new release, which will probably happen on Monday.

But you can fix this error yourself:

Add the following section to settings.yaml:
```
kps4_3l:
    radius: 10.0                    # the radius of the circle shape on which the kite lines, viewed 
                                    #     from the front                                              [m]
    bridle_center_distance: 2.0     # the distance from point the center bridle connection point of 
                                    #     the middle line to the kite                                 [m]
    middle_length:          2.0     # the cord length of the kite in the middle                       [m]
    tip_length:             1.0     # the cord length of the kite at the tips                         [m]
    min_steering_line_distance: 4.0 # the distance between the left and right steering bridle         [m]
                                    #     line connections on the kite that are closest to each other [m]
    width_3l:               20.0    # width of the kite                                               [m]
    aero_surfaces:          10      # the number of aerodynamic surfaces to use per mass point        [-]
```

**Comment by ufechner7** [comment]
Fixed in the new release 3.10.

**Comment by AlshaimaaYounis** [comment]
After installing the new release and the section kps4_3l has been added to the settings.yaml, also the following error has appeared:

[ Info: Creating sysimage ...
Precompiling project...
  96 dependencies successfully precompiled in 619 seconds. 326 already precompiled.
[ Info: PackageCompiler: Executing C:\Users\alsha\OneDrive\Desktop\kiteSims\test\test_for_precompile.jl => C:\Users\alsha\AppData\Local\Temp\jl_packagecompiler_FT04Vi\jl_CA86.tmp
ERROR: LoadError: KeyError: key "kps4_3l" not found
Stacktrace:
 [1] getindex
   @ .\dict.jl:498 [inlined]
 [2] update_settings(dict::Dict{Any, Any}, sections::Vector{String})
   @ KiteUtils C:\Users\alsha\.julia\packages\KiteUtils\Rzc0r\src\settings.jl:306
 [3] se(project::String)
   @ KiteUtils C:\Users\alsha\.julia\packages\KiteUtils\Rzc0r\src\settings.jl:353
 [4] load_settings(project::String)
   @ KiteUtils C:\Users\alsha\.julia\packages\KiteUtils\Rzc0r\src\settings.jl:260
 [5] top-level scope
   @ C:\Users\alsha\OneDrive\Desktop\kiteSims\examples\autopilot.jl:56
 [6] include(fname::String)
   @ Base.MainInclude .\client.jl:489
 [7] top-level scope
   @ C:\Users\alsha\OneDrive\Desktop\kiteSims\test\test_for_precompile.jl:3
in expression starting at C:\Users\alsha\OneDrive\Desktop\kiteSims\examples\autopilot.jl:56
in expression starting at C:\Users\alsha\OneDrive\Desktop\kiteSims\test\test_for_precompile.jl:2
ERROR: LoadError: failed process: Process(setenv(`'C:\Users\alsha\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\bin\julia.exe' --color=yes --startup-file=no --pkgimages=no '--sysimage=C:\Users\alsha\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\lib\julia\sys.dll' --compile=all '--trace-compile=C:\Users\alsha\AppData\Local\Temp\jl_packagecompiler_FT04Vi\jl_CA86.tmp' 'test\test_for_precompile.jl'`,["WINDIR=C:\\WINDOWS", "PATH=C:\\Users\\alsha\\.julia\\conda\\3\\x86_64\\Library\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\MATLAB\\R2023a\\runtime\\win64;C:\\Program Files\\MATLAB\\R2023a\\bin;C:\\Program Files\\MATLAB\\R2022b\\runtime\\win64;C:\\Program Files\\MATLAB\\R2022b\\bin;C:\\Program Files (x86)\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Users\\alsha\\AppData\\Local\\Programs\\Python\\Python311\\Scripts;C:\\Users\\alsha\\AppData\\Local\\Programs\\Python\\Python311;C:\\Program Files\\dotnet\\;C:\\Program Files\\PuTTY\\;C:\\Program Files\\Git\\cmd;C:\\Users\\alsha\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\alsha\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\Brackets\\;C:\\Users\\alsha\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\alsha\\.dotnet\\tools", "USERDOMAIN_ROAMINGPROFILE=SHAY_ASUS", "VERSION_STRING=julia version 1.10.4", "LOCALAPPDATA=C:\\Users\\alsha\\AppData\\Local", "HOMEPATH=\\Users\\alsha", "IMAGE=kps-image-1.10.so", "JULIA_MAJOR=1.10", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel", "NUMBER_OF_PROCESSORS=4"  …  "PROCESSOR_LEVEL=6", "JULIA_LOAD_PATH=C:\\Users\\alsha\\OneDrive\\Desktop\\kiteSims;@stdlib", "SYSTEMDRIVE=C:", "=C:=C:\\Users\\alsha\\OneDrive\\Desktop\\kiteSims", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "PROGRAMW6432=C:\\Program Files", "TEMP=C:\\Users\\alsha\\AppData\\Local\\Temp", "HOMEDRIVE=C:", "OPENBLAS_MAIN_FREE=1", "PROCESSOR_ARCHITECTURE=AMD64"]), ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ .\process.jl:565 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base .\process.jl:480
  [3] run
    @ .\process.jl:477 [inlined]
  [4] run_precompilation_script(project::String, sysimg::String, precompile_file::String,
 precompile_dir::String)
    @ PackageCompiler C:\Users\alsha\.julia\packages\PackageCompiler\nT5sD\src\PackageCompiler.jl:306
  [5] create_sysimg_object_file(object_file::String, packages::Vector{String}, packages_sysimg::Set{Base.PkgId}; project::String, base_sysimage::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, extra_precompiles::String, incremental::Bool)
    @ PackageCompiler C:\Users\alsha\.julia\packages\PackageCompiler\nT5sD\src\PackageCompiler.jl:344
  [6] create_sysimg_object_file
    @ C:\Users\alsha\.julia\packages\PackageCompiler\nT5sD\src\PackageCompiler.jl:311 [inlined]
  [7] create_sysimage(packages::Vector{Symbol}; sysimage_path::String, project::String, precompile_execution_file::String, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, base_sysimage::Nothing, julia_init_c_file::Nothing, julia_init_h_file::Nothing, version::Nothing, soname::Nothing, compat_level::String, extra_precompiles::String)
    @ PackageCompiler C:\Users\alsha\.julia\packages\PackageCompiler\nT5sD\src\PackageCompiler.jl:628
  [8] top-level scope
    @ C:\Users\alsha\OneDrive\Desktop\kiteSims\test\create_sys_image.jl:11
  [9] include(fname::String)
    @ Base.MainInclude .\client.jl:489
 [10] top-level scope
    @ none:1
in expression starting at C:\Users\alsha\OneDrive\Desktop\kiteSims\test\create_sys_image.jl:11
The system cannot find the file specified.
Precompiling project...
  10 dependencies successfully precompiled in 171 seconds. 412 already precompiled.

**Comment by ufechner7** [comment]
Try to delete the folders .julia and kiteSims and try again.

**Comment by AlshaimaaYounis** [comment]
It works well
Thank you very much
