### ISSUE TITLE
Missing Package Timers

### ISSUE THREAD

**Issue by riosnav** [aenarete/KiteSimulators.jl#8]
After following the installation instructions for Windows 11 successfully, I executed the joystick example as instructed:
`include("examples\\joystick.jl")`
And I got the following error message:
`ERROR: LoadError: ArgumentError: Package Timers not found in current path:`
`- Run 'import Pkg; Pkg.add("Timers")' to install the Timers package.`

After installing the Timers package as suggested by the error message everything works as expected.

I would suggest adding Timers as a prerequisite for this package so it is added during the initial installation.

Thank you.

**Comment by ufechner7** [comment]
Well, the package Timers is already a dependency of this package. But in the example **joystick.jl** I try to load Timers before loading this package and that must fail. I updated the installation instructions accordingly.

Thanks for reporting, and feel free to ask if you have any questions about how to use this package.
